services:
  mongodb:
    container_name: "mongodb"
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - GLIBC_TUNABLES=glibc.pthread.rseq=0
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
    networks:
      - backend

  redis:
    container_name: "redis"
    image: "bitnami/redis:latest"
    environment:
      - REDIS_PASSWORD=admin
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
