services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--log.level=ERROR"
      - "--accesslog=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=lfelipecmendes@gmai.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entryPoints.web.forwardedHeaders.insecure"
      - "--entryPoints.websecure.forwardedHeaders.insecure"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock"

  app:
    build:
      context: .
    container_name: todo-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo-app.entrypoints=websecure"
      - "traefik.http.routers.todo-app.tls.certresolver=myresolver"
      - "traefik.http.routers.todo-app.rule=Host(`todo-app.site`)"
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/todo-app?schema=public
      - REDIS_PORT
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_DB
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  postgres:
    container_name: "postgres"
    image: "bitnami/postgresql:latest"
    environment:
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_DATABASE=todo-app
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/bitnami/postgresql"
    networks:
      - backend
    restart: always

  redis:
    container_name: "redis"
    image: "bitnami/redis:latest"
    environment:
      - REDIS_PASSWORD=admin
      - REDIS_USERNAME=admin
      - REDIS_DATABASE_NUMBER=0
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  letsencrypt:
